config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :beds do
    resources :bookings, only: [:create, :new, :edit, :update]
  end
  resources :bookings, except: [:create, :new, :edit, :update]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bed.rb
class Bed < ApplicationRecord
  belongs_to :user
  has_many :bookings
  has_one_attached :photo
  validates :category, presence: true
  validates :ward, presence: true
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :bed
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :beds, dependent: :delete_all
  has_many :bookings, dependent: :delete_all
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:role])
  end
end

app/controllers/beds_controller.rb
class BedsController < ApplicationController
  before_action :set_bed, only: [:show, :destroy]

  def index
    @beds = Bed.all

    # @beds = Bed.all
    if params[:category].present?
      @beds = @beds.where(category: params[:category])
    end
    if params[:address].present?
      @beds = @beds.near(params[:address], 20)
    end
    @markers = @beds.geocoded.map do |bed|
      {
        lat: bed.latitude,
        lng: bed.longitude,
        infoWindow: render_to_string(partial: "info_window", locals: { bed: bed })
        # image_url: helpers.asset_url('/app/assets/images/bf-logo.png')

      }
    end
  end

  def show
    @booking = Booking.new
  end

  def new
    check_role
    @bed = Bed.new
  end

  def create
    @bed = Bed.new(bed_params)
    @bed.user = current_user
    if @bed.save
      redirect_to beds_path, alert: "LISTING CREATED"
    else
      render :new
    end
  end

  def edit
    @bed = Bed.find(params[:id])
  end

  def update
  end

  def destroy
    @bed = Bed.find(params[:id])
    @bed.destroy
    redirect_to beds_path
  end

  private

  def set_bed
    @bed = Bed.find(params[:id])
  end

  def bed_params
    params.require(:bed).permit(:category, :ward, :address, :photo)
  end

  def check_role
    unless current_user.role == "provider"
      redirect_to root_path, alert: "ACCESS DENIED"
    end
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController

  def index
    # @bookings = Booking.all
    @bookings = Booking.where(user_id: current_user.id)
  end

  def new
    @bed = Bed.find(params[:id])
    @booking = Booking.new
  end

  def create
    @booking = Booking.new(booking_params)
    @booking.user_id = current_user.id
    @booking.bed_id = params[:bed_id]
    @booking.start_date = DateTime.now +1.week
    if @booking.save
      redirect_to bookings_path, alert: "booking requested!"
    else
      redirect_to bed_path(params[:bed_id]), alert: "request invalid, please try again"
    end
  end

   def edit
    @bed = Bed.find(params[:bed_id])
    @booking = Booking.find(params[:id])
  end

   def destroy
    @booking = Booking.find(params[:id])
    @booking.destroy
    redirect_to beds_path
  end

  def update
    @booking = Booking.find(params[:id])
    if @booking.update(booking_params)
      redirect_to bookings_path, alert: "booking updated"
    else
      render :edit
    end
  end

  private

  def booking_params
    params.require(:booking).permit(:start_date)
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home
  def home
    @beds = Bed.first(5)
  end

  def search
    if params[:search].blank?
      redirect_to(root_path, alert: "Empty field!") and return
    else
  end
end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/beds/_info_window.html.erb
<h2 class="info"><%= bed.category %></h2>
<p class="info-address"><%= bed.address %></p>

app/views/beds/edit.html.erb
<div class="container">
  <div class="d-block p-4 w-75">
    <h1>Edit your bed</h1>
    <p>Fill out the form below to edit your bed</p>
    <div class="listing-form mt-4">
      <%= simple_form_for @bed do |f| %>
      <%= f.input :category %>
      <%= f.input :ward %>
      <%= f.input :address %>
      <br> <%= f.button :file_field, :photo, as: :file %> </br>
      <br> <%= f.button :submit, class: "btn btn-light border ml-2" %> </br>
      <% end %>
    </div>
  </div>
</div>

app/views/beds/index.html.erb
<div class="container">
  <%= render "shared/searchbar" %>
  <div class="d-flex align-items-start">
    <div class="cards p-3">
      <% @beds.each do |bed| %>
        <%= link_to bed_path(bed) do %>
          <div class="card-product mb-3 p-3">
            <% if bed.photo.attached? %>
              <%= cl_image_tag bed.photo.key %>
            <% else %>
              <img class="rounded" src="https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/skateboard.jpg" />
            <% end %>
            <div class="card-product-infos">
              <h2><%=bed.category%></h2>
              <p><strong><%= bed.ward %></strong> - <%= bed.address %></p>
            </div>
          </div>
            <p>

            </p>
        <% end %>
      <% end %>
    </div>
    <div id="map" class="rounded"
      style= "height: 80vh;"
       data-markers="<%= @markers.to_json %>"
       data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
    </div>
  </div>
</div>

app/views/beds/new.html.erb
<div class="container">
  <div class="d-flex justify-content-center">
    <div class="d-block">
      <h1 class="mt-4 mb-3">List your bed</h1>
      <p>Fill out the form below to list your bed</p>
      <div class="listing-form mt-4">
        <%= simple_form_for @bed do |f| %>
        <%= f.input :category %>
        <%= f.input :ward %>
        <%= f.input :address %>
        <br> <%= f.button :file_field, :photo, as: :file %> </br>
        <br> <%= f.button :submit, class: "btn btn-light border ml-2" %> </br>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/beds/show.html.erb
<div class="container d-block">
  <div class="p-3">
    <h1 class="text-center"><%= "Ward name: #{@bed.ward}"%></h1>
    <h2 class="text-center"><%= "Category: #{@bed.category}"%></h2>
  </div>
  <div class="pt-5 d-flex justify-content-center">
    <% if @bed.photo.attached? %>
      <%= cl_image_tag @bed.photo.key, width: 800, height: 500, crop: :fill, class:"shadow-sm rounded" %>
    <% end %>
  </div>
  <div class="pt-4 pr-4 pb-4 pl-0 text-left">
    <h2>Description</h2>
    <p class="font-weight-light">This is the perfect bed for patients that are looking for a safe place to recover. The staff are wonderfully attentive and have the patients needs at the forefront of their minds.</p>
  </div>
</div>

<div class="booking-form pb-4">
  <%= render "shared/booking_form" %>
</div>

app/views/bookings/edit.html.erb
<div class="container">
  <h1 class="text-center m-4">Edit your booking</h1>
  <p class="text-center m-4">Fill out the form below<br>to edit your booking</p>
  <div class="d-flex justify-content-center mt-5">
    <div class="w-50">
      <%= render "shared/booking_form" %>
    </div>
  </div>
</div>

app/views/bookings/index.html.erb
<div class="container w-75">
  <h1 class="text-center my-4">Your Bookings</h1>
  <ul class="list-group">
    <% @bookings.each do |booking| %>
      <li class="list-group-item d-flex justify-content-between align-items-center m-2">
        <div class="category text-center font-weight-bold" style="width:80px;">
          <%= booking.bed.category %>
        </div>
        <span class="badge badge-primary badge-pill p-3"><%= booking.start_date %></span>
        <div class="btn btn-outline-primary text-primary">
          <%= link_to "Delete", booking_path(booking), method: :delete, data: { confirm: "Are You Sure" }, :class => "btn" %>
        </div>
        <div class="btn btn-outline-primary text-primary">
          <%= link_to "Edit", edit_bed_booking_path(booking.bed, booking), :class => "btn" %>
        </div>
      </li>
    <% end %>
  </ul>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BedFinder</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flash' %>
    <script src="https://cdn.jsdelivr.net/npm/typed.js@2.0.11"></script>
    <div class="main-content">
      <%= yield %>
    </div>
    <%= render 'shared/footer' %>
  </body>
</html>

app/views/pages/about.html.erb
<h1>About us</h1>

app/views/pages/home.html.erb
<head>

</head>

<body>
  <div class="banner" style=" height: 400px; background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://images.unsplash.com/photo-1477332552946-cfb384aeaf1c?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=750&q=80);">
    <div class="container">
      <span class="typed"></span>
    </div>
  </div>
  <div class="m-4">
    <%= render "shared/searchbar" %>
  </div>
  <div class="container">
    <h2 id="centering-title">Beds available in your area</h2>
    <% @beds.each do |bed| %>
      <%= link_to bed_path(bed) do %>
        <div class="card-product mb-3 p-3">
          <% if bed.photo.attached? %>
            <%= cl_image_tag bed.photo.key %>
          <% else %>
            <img class="rounded" src="https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/skateboard.jpg" />
          <% end %>
          <div class="card-product-infos">
            <h2><%=bed.category%></h2>
            <p><strong><%= bed.ward %></strong> - <%= bed.address %></p>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>
</body>

app/views/shared/_booking_form.html.erb
<div class="container" >
  <%= simple_form_for [@bed, @booking] do |f| %>

  <%= f.input :start_date,
              as: :date,
              html5: true,
              label: "When are you starting to book this bed?",
              required: true %>
  <br>
  <%= f.button :submit, "Request this bed", class: "btn btn-secondary"%>
  <% end %>
</div>

app/views/shared/_card.html.erb
<!-- <div class="card-deck"> -->
<div class="container-fluid mt-4">
  <div class="row justify-content-center">
    <div class="col-auto mb-3">
      <div class="card h-75">
        <img class="card-img-top" src="https://www.weymouthstreethospital.com/wp-content/uploads/sites/2/2019/05/room1-1024x683.jpg" alt="Card image cap">
        <div class="card-body d-block">
          <h5 class="card-title text-left">Hospital Name</h5>
          <h6 class="card-text">Hospital Description</h6>
          <h6 class="card-text"><small class="text-muted">Category</small></h6>
        </div>
      </div>
    </div>
    <div class="col-auto mb-3">
      <div class="card h-75">
        <img class="card-img-top" src="https://www.weymouthstreethospital.com/wp-content/uploads/sites/2/2019/05/room1-1024x683.jpg" alt="Card image cap">
        <div class="card-body">
          <h5 class="card-title">Hospital Name</h5>
          <p class="card-text">Hospital Description</p>
          <p class="card-text"><small class="text-muted">Category</small></p>
        </div>
      </div>
    </div>
    <div class="col-auto mb-3">
      <div class="card h-75">
        <img class="card-img-top" src="https://www.weymouthstreethospital.com/wp-content/uploads/sites/2/2019/05/room1-1024x683.jpg" alt="Card image cap">
        <div class="card-body">
          <h5 class="card-title">Hospital Name</h5>
          <p class="card-text">Hospital Description</p>
          <p class="card-text"><small class="text-muted">Category</small></p>
        </div>
      </div>
    </div>
    <div class="col-auto mb-3">
      <div class="card h-75">
        <img class="card-img-top" src="https://www.weymouthstreethospital.com/wp-content/uploads/sites/2/2019/05/room1-1024x683.jpg" alt="Card image cap">
        <div class="card-body">
          <h5 class="card-title">Hospital Name</h5>
          <p class="card-text">Hospital Description</p>
          <p class="card-text"><small class="text-muted">Category</small></p>
        </div>
      </div>
    </div>
  </div>
</div>
<!--   </div>
</div> -->

app/views/shared/_flash.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer bg-white">
  <div class="footer-links">
    <a href="#" class="text-primary"><i class="fab fa-github"></i></a>
    <a href="#" class="text-primary"><i class="fab fa-instagram"></i></a>
    <a href="#" class="text-primary"><i class="fab fa-facebook"></i></a>
    <a href="#" class="text-primary"><i class="fab fa-twitter"></i></a>
    <a href="#" class="text-primary"><i class="fab fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright text-primary">
    Bedfinder is made with <i class="fas fa-heart"></i> @ Le Wagon by team Good Booking
  </div>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light navbar-lewagon">
    <%= link_to root_path, class: "navbar-brand" do %>
  <%= image_tag "bed-finder-logo.png", alt: "alttext" %>
    <% end %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item active">
          <% if current_user.role == 'consumer' %>
            <%= link_to "My Bookings", bookings_path, class: "nav-link text-primary" %>
          <% else %>
            <%= link_to "My Bookings", bookings_path, class: "nav-link text-primary" %>
          <% end %>
        </li>
        <li class="nav-item">
          <%= link_to "List Bed", new_bed_path, class: "nav-link text-primary" %>
          </li>
          <li>
          <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "nav-link text-primary" %>
        </li>
      <% else %>
      <li class="nav-item active">
        <a class="nav-link text-primary" href="#">About us <span class="sr-only">(current)</span></a>
      </li>

      <li class="nav-item dropdown">
        <a class="nav-link text-primary dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          How it works
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="#">Find a bed</a>
          <a class="dropdown-item" href="#">List a bed</a>
        </div>
      </li>
      <li class="nav-item">
        <a class="nav-link text-primary active" href="#">Register a bed</a>
      </li>
    </ul>
    <a class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "btn btn-primary" %>

        </a>
        <% end %>
  </div>
</nav>

app/views/shared/_searchbar.html.erb
<div class="Search pt-3">
  <div class="container">
    <form class="form-inline" action="/beds">
    <label class="sr-only" for="inlineFormInputName2">Category</label>
    <input type="text" name="category" class="form-control mb-2 mr-sm-2" id="inlineFormInputName2" placeholder="Category">

<!--     <label class="sr-only" for="formPlaceholder2">Date</label>
    <div class="input-group mb-2 mr-sm-2">
        <div class="input-group-prepend">
        </div>
        <input type="text" name="date" class="form-control" id="formPlaceholder2" placeholder="Date">
    </div> -->

    <label class="sr-only" for="formPlaceholder3">Address</label>
    <div class="input-group mb-2 mr-sm-2">
        <div class="input-group-prepend">
        </div>
        <input type="text" name="address" class="form-control" id="formPlaceholder3" placeholder="Address">
    </div>

      <input type="submit" class="btn btn-primary mb-2">
      <!-- <a href="/beds" class="btn btn-primary btn-lg active" role="button" aria-pressed="true">Find</a> -->
    </form>
  </div>
</div>